spring:
  application:
    name: auth-service
  server:
    port: 8081

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_onbase_auth
    username: miniuser
    password: minipassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.jdbc.time_zone: UTC

  app:
    default-roles: ROLE_USER

jwt:
  secret: hG8r9X2k3Lqf7ZpQ1mT6vU8yN4cR0sA2bC4dE6fG7hI8jK9lM0nP1qR2sT3uV4W
  issuer: mini-onbase
  expires-minutes: 60
